-- Enable RLS on tables that are missing it
ALTER TABLE IF EXISTS public.owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.mascotas ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.mascota_duenos ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.knowledge_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.bot_contacts ENABLE ROW LEVEL SECURITY;